
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-api
  template:
    metadata:
      labels:
        app: helloworld-api
    spec:
      containers:
      - name: helloworld-api
        image: <your-dockerhub-username>/helloworld-api:latest
        ports:
        - containerPort: 3000
